/*
 * File: app/view/LandingPage.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LandingPage', {
    extend: 'Ext.container.Viewport',

    requires: [
        'MyApp.view.SearchPanel',
        'MyApp.view.MapResultPanel'
    ],

    style: '{\r\n    background-color: grey\r\n}',
    layout: {
        align: 'stretch',
        type: 'hbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'mypanel',
                    flex: 1
                },
                {
                    xtype: 'mypanel11',
                    flex: 1
                }
            ]
        });

        me.callParent(arguments);
    }

});